/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as PoliticaPrivacidadeRouteImport } from './routes/politica-privacidade'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BairrosRouteImport } from './routes/bairros'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AtendimentoIndexRouteImport } from './routes/atendimento.index'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AtendimentoBairroRouteImport } from './routes/atendimento.$bairro'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadeRoute = PoliticaPrivacidadeRouteImport.update({
  id: '/politica-privacidade',
  path: '/politica-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BairrosRoute = BairrosRouteImport.update({
  id: '/bairros',
  path: '/bairros',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AtendimentoIndexRoute = AtendimentoIndexRouteImport.update({
  id: '/atendimento/',
  path: '/atendimento/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/servicos/$slug',
  path: '/servicos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AtendimentoBairroRoute = AtendimentoBairroRouteImport.update({
  id: '/atendimento/$bairro',
  path: '/atendimento/$bairro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bairros': typeof BairrosRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/obrigado': typeof ObrigadoRoute
  '/orcamento': typeof OrcamentoRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/projetos': typeof ProjetosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/atendimento/$bairro': typeof AtendimentoBairroRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/atendimento/': typeof AtendimentoIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bairros': typeof BairrosRoute
  '/contato': typeof ContatoRoute
  '/obrigado': typeof ObrigadoRoute
  '/orcamento': typeof OrcamentoRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/projetos': typeof ProjetosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/atendimento/$bairro': typeof AtendimentoBairroRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/atendimento': typeof AtendimentoIndexRoute
  '/blog': typeof BlogIndexRoute
  '/servicos': typeof ServicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bairros': typeof BairrosRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/obrigado': typeof ObrigadoRoute
  '/orcamento': typeof OrcamentoRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/projetos': typeof ProjetosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/atendimento/$bairro': typeof AtendimentoBairroRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/atendimento/': typeof AtendimentoIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bairros'
    | '/blog'
    | '/contato'
    | '/obrigado'
    | '/orcamento'
    | '/politica-privacidade'
    | '/projetos'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/atendimento/$bairro'
    | '/blog/$slug'
    | '/servicos/$slug'
    | '/atendimento/'
    | '/blog/'
    | '/servicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bairros'
    | '/contato'
    | '/obrigado'
    | '/orcamento'
    | '/politica-privacidade'
    | '/projetos'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/atendimento/$bairro'
    | '/blog/$slug'
    | '/servicos/$slug'
    | '/atendimento'
    | '/blog'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bairros'
    | '/blog'
    | '/contato'
    | '/obrigado'
    | '/orcamento'
    | '/politica-privacidade'
    | '/projetos'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/atendimento/$bairro'
    | '/blog/$slug'
    | '/servicos/$slug'
    | '/atendimento/'
    | '/blog/'
    | '/servicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BairrosRoute: typeof BairrosRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  ObrigadoRoute: typeof ObrigadoRoute
  OrcamentoRoute: typeof OrcamentoRoute
  PoliticaPrivacidadeRoute: typeof PoliticaPrivacidadeRoute
  ProjetosRoute: typeof ProjetosRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  AtendimentoBairroRoute: typeof AtendimentoBairroRoute
  ServicosSlugRoute: typeof ServicosSlugRoute
  AtendimentoIndexRoute: typeof AtendimentoIndexRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidade': {
      id: '/politica-privacidade'
      path: '/politica-privacidade'
      fullPath: '/politica-privacidade'
      preLoaderRoute: typeof PoliticaPrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bairros': {
      id: '/bairros'
      path: '/bairros'
      fullPath: '/bairros'
      preLoaderRoute: typeof BairrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/atendimento/': {
      id: '/atendimento/'
      path: '/atendimento'
      fullPath: '/atendimento/'
      preLoaderRoute: typeof AtendimentoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/servicos/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/atendimento/$bairro': {
      id: '/atendimento/$bairro'
      path: '/atendimento/$bairro'
      fullPath: '/atendimento/$bairro'
      preLoaderRoute: typeof AtendimentoBairroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BairrosRoute: BairrosRoute,
  BlogRoute: BlogRouteWithChildren,
  ContatoRoute: ContatoRoute,
  ObrigadoRoute: ObrigadoRoute,
  OrcamentoRoute: OrcamentoRoute,
  PoliticaPrivacidadeRoute: PoliticaPrivacidadeRoute,
  ProjetosRoute: ProjetosRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  AtendimentoBairroRoute: AtendimentoBairroRoute,
  ServicosSlugRoute: ServicosSlugRoute,
  AtendimentoIndexRoute: AtendimentoIndexRoute,
  ServicosIndexRoute: ServicosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
